# Generated by Django 3.2.9 on 2021-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='blog/image'),
        ),
    ]
